title: Computational Biology Workshop
logo: /img/2pfsb_logo.png
description: This workshop was presented at the 2nd Panhellenic Conference for Students Bioscientists (2PFSB). Data was taken after request from a published Research Article: N.Karagianni et al.(2019). DOI: https://doi.org/10.1371/journal.pcbi.1006933

#show_downloads: true
theme: jekyll-theme-minimal
