title: Computational Biology Workshop
logo: /img/2pfsb_logo.png
description: This workshop was presented at the 2nd Panhellenic Conference for Students Bioscientists (2PFSB)
#show_downloads: true
theme: jekyll-theme-minimal
